# Generated by Django 4.1.5 on 2023-01-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pass", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pass",
            new_name="Password",
        ),
        migrations.RenameField(
            model_name="password",
            old_name="pw",
            new_name="password",
        ),
    ]
